#!/bin/sh
set -e

while getopts ":e:" opt; do
  case $opt in
    e) env_name="$OPTARG"
    shift
    ;;
    --) shift; break;;
    *) # handle unrecognized arg
    ;;
  esac
  shift
done

if [ -z ${env_name+x} ]; then
  if [ -f .env ]; then
    echo "Loading default environment..."
    export $(cat .env | grep -v '^\#' | xargs)
  else
    echo ".env file required. Run makenv?"; exit 1
  fi
else
  if [ -f .${env_name}.env ]; then
    echo "Loading ${env_name} environment..."
    export $(cat .${env_name}.env | grep -v '^\#' | xargs)
  else
    echo ".${env_name}.env file required. Run makenv -e $env_name?"
  fi
fi

exec "$@"
