#!/bin/bash

printf 'Lets do(t) this!\n'

while getopts ":e:" opt; do
  case $opt in
    e) env_name="$OPTARG"
    ;;
    *)
    ;;
  esac
done

envfile="# Generated environment file"

keepgoing=true
while [ keepgoing ]; do
  read -p "Enter variable name [done]: " name
  if [ -z "$name" -a "${name+xxx}" = "xxx" ]
  then
    break
  else
    read -p "Enter value for $name: " value
    envfile+=$'\n'$"$name"$'='$"$value"
  fi
done

if [ -z ${env_name+x} ]; then
  echo 'Writing .env file...'
  echo "$envfile" > .env
  cat .env
else
  echo "Writing .${env_name}.env file..."
  echo "$envfile" > ".${env_name}.env"
  cat ".${env_name}.env"
fi
